/*
 *
 *    srtm
 *
 */

/* Written by Sam Blake. */

/* Started on 17 Feb 2016. */

/* This program incorperates SRTM data (or any arcinfo ascii
gridded data) into a user specified ascii grid. The input grid
must have NODATA_value (s) at points where the land data from 
SRTM is to be interpolated. The output file is overwritten. 

Information on SRTM data can be found at 

    http://www2.jpl.nasa.gov/srtm/

*/

/*
    Command line inputs: 

      -input /name of input .asc formatted file/

      -output /name of the output .asc formatted file/

      -srtm /file containing a list of the .asc SRTM data files./


The file containing the list of SRTM files can be generated by changing 
directory to the folder containing the SRTM files and running 

  $   ls -1 $PWD/srtm*.asc 

and piping the output to file. 

This program was also used to convert the 64 tiles of the Australian 
bathymetry database into a single asc grid. 

*/

#include "srtm.h"
#include "common.h"
#include "io.h"
#include "interp.h"


#define MXFILE 512

int main(int argc, char **argv) {

  int i, j, n, nx_raw, ny_raw, nx, ny, updated;
  char inputfile[MXFILE], outputfile[MXFILE], srtmfiles[MXFILE], filename[MXFILE];
  FILE *fp;
  float **grid_raw, **grid, height; 
  double wlon_raw, slat_raw, cellsize_raw, spval_raw, wlon, slat, cellsize, spval,
    elon_raw, nlat_raw, elon, nlat, lat, lon;

  // Read command line inputs. 

  for (n = 1; n < argc; n++) {
    if (strcmp(argv[n], "-input") == 0) {
      strcpy(inputfile, argv[++n]);
      printf("-input %s\n", inputfile);
    } else if (strcmp(argv[n], "-output") == 0) {
      strcpy(outputfile, argv[++n]);
      printf("-output %s\n", outputfile);
    } else if (strcmp(argv[n], "-srtm") == 0) {
      strcpy(srtmfiles, argv[++n]);
      printf("-srtm %s\n", srtmfiles);
    } else {
      printf("\nERROR: unknown option:  %s\n\n", argv[n]);
      exit(1);
    }
  }

  // Check input and srtm files exist. 
  if (! file_exists(inputfile)) {
    printf("\nERROR: missing file: %s\n", inputfile);
    exit(1);
  }

  if (! file_exists(srtmfiles)) {
    printf("\nERROR: missing file: %s\n", srtmfiles); 
    exit(1);
  }
  

  // Read in input grid file. 
  read_asc(inputfile, &grid_raw, &nx_raw, &ny_raw, &wlon_raw, &slat_raw, &cellsize_raw, &spval_raw);
  nlat_raw = slat_raw + (ny_raw - 1)*cellsize_raw;
  elon_raw = wlon_raw + (nx_raw - 1)*cellsize_raw;

  // Loop over all files. 
  fp = fopen(srtmfiles, "r");

  while (!feof(fp)) {
    // Read SRTM file name. 
    fgets(filename, sizeof(filename), fp);
    // printf("%s", filename); 
    
    // Check SRTM file exists.
    if (! file_exists(trim(filename))) {
      printf("\nWARNING: missing file: %s\n", filename);
      continue ;
    }

    // Read header data from SRTM file. 
    read_asc_header(filename, &nx, &ny, &wlon, &slat, &cellsize, &spval);
    nlat = slat + (ny - 1)*cellsize; 
    elon = wlon + (nx - 1)*cellsize;

    // Compare extents of the two grids - checking for any intersection. 
    if ( overlap(wlon_raw, elon_raw, slat_raw, nlat_raw,
		 wlon, elon, slat, nlat) ) {
      printf("\nInterpolating data from: %s\n", filename); 
      // Read the grid into memory.
      read_asc(filename, &grid, &nx, &ny, &wlon, &slat, &cellsize, &spval);
      // Interpolate SRTM data into raw grid. 
      updated = 0;
      for (i = 0; i < ny_raw; i++) {
	     for (j = 0; j < nx_raw; j++) {
	       lon = wlon_raw + ((double) j)*cellsize_raw;
	       lat = slat_raw + ((double) i)*cellsize_raw;
	       if (grid_raw[i][j] == spval_raw && 
	         lon >= wlon && lon <= elon && lat >= slat && lat <= nlat) {
	         updated++;
	         height = interp_bicubic(grid, nx, ny, wlon, slat, cellsize, spval, lon, lat);
	         if (height == spval) {
	          printf("\nWARNING: land data missing.\n"); 
            grid_raw[i][j] = spval_raw;
           } else {
             grid_raw[i][j] = height;
           }
	       }
	     }
      }
      printf("\nUpdated %d land points.\n", updated);

    // Free memory. 
    free_float_array_2d(grid, ny);
    }
  }

  fclose(fp);

  // Write out updated asci grid. 
  write_asc(outputfile, grid_raw, nx_raw, ny_raw, wlon_raw, slat_raw, cellsize_raw, spval_raw);

  // Free memory. 
  free_float_array_2d(grid_raw, ny_raw);

  printf("\n\n");

  return 0;
}

